### ISSUE TITLE
0.0.8 Doesn't work

### ISSUE THREAD

**Issue by jramstedt** [ckeditor/strapi-plugin-ckeditor#79]
After upgrading to 0.0.8 ckeditor plugin doesn't work anymore.
I also tried with clean install:
```
yarn create strapi-app ckeditortest --quickstart --ts --no-run
cd ckeditortest
yarn add @ckeditor/strapi-plugin-ckeditor
yarn build
yarn develop
```

Trying to edit collection type with ckeditor field just shows loading animation and starts to throw errors into console ~100 per second.

```
Uncaught (in promise) ReferenceError: Cannot access 'Qe' before initialization
    at Module.default (5220.5686afc6.chunk.js:178:428)
    at content-manager.d1b9ee11.chunk.js:155:1294
    at Array.forEach (<anonymous>)
    at m (content-manager.d1b9ee11.chunk.js:155:1264)
default @ 5220.5686afc6.chunk.js:178
(anonymous) @ content-manager.d1b9ee11.chunk.js:155
m @ content-manager.d1b9ee11.chunk.js:155
await in m (async)
(anonymous) @ content-manager.d1b9ee11.chunk.js:155
js @ main.26a9a14c.js:1258
Zc @ main.26a9a14c.js:1258
(anonymous) @ main.26a9a14c.js:1258
L @ main.26a9a14c.js:1329
ve @ main.26a9a14c.js:1329
```

**Comment by ruohki** [comment]
also encountering this on Strapi 4.12.0

**Comment by NASlR** [comment]
yep same installed on strapi 4.6.1 and got an error after building and trying to load the custom field 
```typeerror: m[a] is not a function```

**Comment by Mgsy** [comment]
Thanks for the report. I will check what is going on.

**Comment by Mgsy** [comment]
@jramstedt @ruohki @NASlR I've just released a fixed package. Could you update to `v0.0.9` and see if the issue is gone?

**Comment by colonder** [comment]
@Mgsy no, it still show the error
```
8107.634b3899.chunk.js:129  Uncaught (in promise) ReferenceError: Cannot access 'Fe' before initialization
    at Module.default (8107.634b3899.chunk.js:129:2918)
    at content-manager.51c30392.chunk.js:155:1307
    at Array.forEach (<anonymous>)
    at u (content-manager.51c30392.chunk.js:155:1277)
default @ 8107.634b3899.chunk.js:129
(anonymous) @ content-manager.51c30392.chunk.js:155
u @ content-manager.51c30392.chunk.js:155
await in u (async)
(anonymous) @ content-manager.51c30392.chunk.js:155
Nu @ main.35a5022f.js:2153
Rd @ main.35a5022f.js:2153
(anonymous) @ main.35a5022f.js:2153
D @ main.35a5022f.js:2246
G @ main.35a5022f.js:2246
```

**Comment by Mgsy** [comment]
> @Mgsy no, it still shows the error

Did you remove `yarn.lock` and `node_modules`? I was testing the released package and couldn't reproduce the issue.

**Comment by colonder** [comment]
Will do it, and get back to you

**Comment by colonder** [comment]
@Mgsy  It seems it works fine

**Comment by Mgsy** [comment]
> @Mgsy It seems it works fine

Great to hear it. As the issue has been solved, I'm closing this ticket.
